[package]
name = "dsv_writer"
version = "0.2.0"
edition = "2024"
publish = ["kellnr"]

[dev-dependencies]
mockall = "*"

[dependencies]
thiserror = "*"
anyhow = "*"
predicates-core = "1.0.9"
common_errors = { version = "*", registry = "kellnr" }