[package]
name = "playground"
version = "0.1.0"
edition = "2024"


[dev-dependencies]
criterion = "*"

[dependencies]
dsv_writer = { path = "../dsv_writer" }
anyhow = "*"
rand_xoshiro = "*"
rand_distr = "*"
rand = "*"
rand_pcg = "*"


[[bench]]
name = "bench"
harness = false